### ISSUE TITLE
Memory leaks. Cells is never release.

### ISSUE THREAD

**Issue by constantine-fry** [kolinkrewinkel/KKGridView#120] opened 2012-03-30 18:30 UTC
I use KKGridView in non-ARC project. I created a subclass of `KKGridViewCell`. An instance of my custom cell is never released.

In order to fix this leak, I updated `KKGridView.m`.

``` objc
- (void)dealloc
{
    [self removeGestureRecognizer:_selectionRecognizer];
    [self _cleanupMetrics];

    _reusableCells = nil;
    _visibleCells = nil;
    _selectedIndexPaths = nil;
    _updateStack = nil;
    _selectionRecognizer = nil;
}
```

**Comment by jonsterling** [comment] 2012-03-30 18:36
This shouldn't be necessary under any circumstances; in any case, it shouldn't stop your cell from leaking.

So, are you sure that your project configuration is correct? That is, `KKGridView` _must_ be compiled with ARC on. Your main target may of course be compiled with ARC off.

**Comment by constantine-fry** [comment] 2012-03-30 18:40
yes, i compiled KKGridView with ARC on.

**Comment by jonsterling** [comment] 2012-03-30 18:47
Hmmm. I'm still very skeptical of this. My deeper concern is that nilling out `__strong` instance variables is _not_ necessary under ARC. In fact, it should have exactly effect at all on whether the objects are released. So, if your change is somehow solving your problem, it has to be a coincidence.

Here's my suggestion for diagnosing the problem:
1. Create a new test project with all code in ARC-mode. This project should contain two things: `KKGridView`, and your `KKGridViewCell` subclass, modified to run under ARC.
2. See if there are any leaks. If it does leak, then there is a problem with `KKGridView` that we should fix.
3. If it does not leak, then proceed to disable ARC for your custom cell class only; adjust your code accordingly. If it now leaks, then there is probably a problem with `KKGridView` that we should fix.
4. If it still does not leak, then the problem is elsewhere in your application and not related to `KKGridView`.

**Comment by jonsterling** [comment] 2012-04-03 22:47
I'm going to close this issue for now, since I can't reproduced the problem, and the solution you propose isn't correct in either case. Please let me know if you have any further information, and we can reopen it!

Best wishes,
Jon

**Closed as completed by jonsterling** 2012-04-03 22:47 UTC
